### ISSUE TITLE
psr/cache V3 and psr/simple-cache V3 compatibilities

### ISSUE THREAD

**Issue by mayottecummings-seedbox** [laminas/laminas-cache#253] opened 2023-01-10 16:12 UTC
Hello,

Since the library is not compatible with psr/cache V2 or V3, it's impossible to upgrade a project using Symfony to the latest version (V6). Eventually, it could lead to problems with newest version of PHP.

Can we have a date or at least an expected one for the next update/version of laminas-cache ?

Best regards :)

**Comment by Ocramius** [comment] 2023-01-12 15:27
Duplicate of #133

**Closed as completed by Ocramius** 2023-01-12 15:27 UTC
Labels: BC Break, Duplicate
